employee:
  getByCredentials:
    SELECT
      employee_cid AS ci,
      employee_email AS email,
      employee_name AS name,
      employee_passwd AS passwd,
      phone_num
    FROM
      employee
    WHERE
      employee_cid = $1

counter:
  testQuery: |
    SELECT 1 AS value

shipment:
  getByStatus:
    SELECT
      shipment_id,
      guide_num,
      client_cid,
      receiver_cid,
      package_id,
      delivery_id,
      status_id,
      destination_branch,
      destination_address,
      shipment_dt
    FROM
      shipment
    WHERE
      status_id = $1    